# -*- coding: utf-8 -*-
"""Assessment_1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1BwargAiWR-D1Ry1emZ3SJViFYVWmB6Om
"""

#1 area of the rectangle
length=int(input("Enter the length:"))
width=int(input("Enter the width:"))
area=length*width
print(area)

#2 BMI calculator
weight=int(input("Enter the weight in kilograms!"))
height=float(input("Enter the h1eight in meters!"))
bmi=(weight/(height**2))
print(bmi)

#3 Dictionary to store student names and scores
dict_1={}
for i in range(1,5):
  key=input("Enter the student name!")
  value=int(input("Enter the score.. "))
  dict_1[key]=value
print(dict_1)

#4 age
age=int(input("Enter the age:"))
if age<18:
  print("minor!")
elif age>=18 and age<=25:
 print("adult!")
else:
  print("senior!")

#5 print even numbers(1-50)
print("Even numbers are..")
for i in range(1,50):
  if i%2==0:
    print(i)

#6 password prompt
def prompt(password):
    while True:
        password = input("Enter the password: ")
        if password == password:
            print("the password is correct!")
            break
        else:
            print("Incorrect password. Try again.")
password = "passwordanjali"
prompt(password)

#7 function
def average_func(list1):
  average=sum(list1)/len(list1)
  return average
list1=[1,2,3,4,5,6,7,8,9,10]
result=average_func(list1)
print("Average of the given list is:",result)

#8 count the number of vowels
def count_vowels(value):
  c=0
  for i in value:
    if i=='a' or i=='e' or i=='i' or i=='o' or i=='u':
     c=c+1
    else:
     continue
  return c;
value=input("Enter the string:")
result=count_vowels(value)
print("count:",result)

#9 date and time
from datetime import datetime
current_time=datetime.now()
print("The current date and time is:",current_time)

#10 non-numeric inputs
def nonnumeric():
    try:
        add = 5 + "anjali"
        print("The sum is:", add)
    except TypeError:
        print("ERROR: Please provide numeric data types!")
nonnumeric()

#11 valueerror
def nonnumeric(data1, data2):
    try:
        add = data1 + data2
        print("The sum is:", add)
    except TypeError:
        print("ERROR: Please provide numeric data types!")
try:
    data1 = int(input("Enter the number 1: "))
    data2 = int(input("Enter the number 2: "))
    nonnumeric(data1, data2)
except ValueError:
    print("ERROR: Please provide numeric input!")

#12 division by zero error
def func():
 try:
  print(var_1/var_2)
 except:
  print('division by zero exception..,just try with some other valu')
func()
var_1=100
var_2=0

#13 file write
my_file=open('/content/sample_data/hello','w')
list1=[]
list1.append("Hello world")
my_file.writelines(list1)
my_file.close()

#14 read and print
my_file=open('/content/sample_data/hello','r')
print(my_file.read())
my_file.close()

# 15 adding new line
file_path = '/content/sample_data/hello'
with open(file_path, 'w') as file:
    list1 = ["hi i am anjali\n", "hello world\n"]
    file.writelines(list1)
with open(file_path, 'a') as file:
    file.write("completed assessment!\n")